apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: 
      $text: 'https://raw.githubusercontent.com/Redocly/openapi-template/refs/heads/gh-pages/openapi.yaml'
