apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-with-docs
  description: The place to be, for great artists
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: 'pranavborude/go-web-app'
    github.com/project-slug: 'ONDC-Organization/ondc-infra-resources'
spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
